[package]
name = "secubot"
version = "0.4.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1" }
serenity = { version = "0.11", default-features = false, features = ["client", "cache", "gateway", "http", "model", "rustls_backend", "unstable_discord_api"] }
tokio = { version = "1.15",	features = ["full"] }
diesel = { version = "1.4", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "1.4" }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = { version = "1.0" }
regex = { version = "1.5" }
lazy_static = { version = "1.4" }
itertools = { version = "0.8" }
config = { version = "0.13" }
glob = { version = "0.3" }
log = { version = "0.4", features = ["std", "serde"] }
env_logger = { version = "0.9" }
