[package]
name = "secubot"
version = "0.1.2"
edition = "2021"

[dependencies]
async-trait = { version = "0.1.52" }
serenity = { version = "0.11.1", default-features = false, features = ["client", "cache", "gateway", "http", "model", "rustls_backend", "unstable_discord_api"] }
tokio = { version = "1.15.0",	features = ["full"] }
diesel = { version = "1.4.8", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "1.4.0" }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = { version = "1.0.137" }
regex = { version = "1.5.5" }
lazy_static = { version = "1.4.0" }
itertools = { version = "0.8.0" }
config = { version = "0.13.1" }
glob = { version = "0.3.0" }
