name: Code quality

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: cargo clippy --all-features -- -D warnings


  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --all -- --check
